-- DEPRECATED: Material Intelligence OCR extensions removed from the app.
-- If your database still has MI tables/columns from a prior deploy, run:
--   supabase/drop-material-intelligence-module.sql
-- New installs only need: expense-invoices-module.sql
